import React, { useState } from 'react'
import { Document, Page, Text, View, StyleSheet, PDFDownloadLink, Image, Font } from '@react-pdf/renderer'
import { generateSARNarrative, TransactionInput } from '@/lib/ml-api'
import { Icon } from './Icon'

// Register fonts if needed (using default for now)
Font.register({
  family: 'Roboto',
  src: 'https://cdnjs.cloudflare.com/ajax/libs/ink/3.1.10/fonts/Roboto/roboto-regular-webfont.ttf'
})

const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    padding: 40,
    fontFamily: 'Roboto'
  },
  header: {
    marginBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: '#10B981', // Emerald-500
    paddingBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center'
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#064E3B' // Emerald-900
  },
  subtitle: {
    fontSize: 10,
    color: '#6B7280'
  },
  section: {
    margin: 10,
    padding: 10,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 8,
    color: '#065F46', // Emerald-800
    backgroundColor: '#ECFDF5', // Emerald-50
    padding: 4
  },
  text: {
    fontSize: 11,
    lineHeight: 1.5,
    marginBottom: 5,
    textAlign: 'justify'
  },
  row: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    paddingVertical: 4,
    alignItems: 'center'
  },
  label: {
    width: 120,
    fontSize: 10,
    fontWeight: 'bold',
    color: '#374151'
  },
  value: {
    fontSize: 10,
    color: '#111827'
  },
  table: {
    display: 'flex',
    width: 'auto',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginTop: 10
  },
  tableRow: {
    margin: 'auto',
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  tableCol: {
    width: '20%',
    borderRightWidth: 1,
    borderRightColor: '#E5E7EB',
    padding: 5
  },
  tableCell: {
    margin: 'auto',
    marginTop: 5,
    fontSize: 9
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    fontSize: 8,
    color: '#9CA3AF',
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    paddingTop: 10
  }
});

interface SARReportProps {
  caseId: string
  transactions: any[] // Using any for flexibility mapping to TransactionInput
  analystNotes?: string
  analystName?: string
}

// The PDF Document Definition
const SARDocument = ({ caseId, transactions, narrative, analystName }: { caseId: string, transactions: any[], narrative: string, analystName: string }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <View>
          <Text style={styles.title}>Suspicious Activity Report</Text>
          <Text style={styles.subtitle}>Generated by CloverShield AI • Strictly Confidential</Text>
        </View>
        <Text style={{ fontSize: 10, color: '#10B981' }}>{new Date().toLocaleDateString()}</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Case Information</Text>
        <View style={styles.row}>
          <Text style={styles.label}>Case ID:</Text>
          <Text style={styles.value}>{caseId}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Reporting Entity:</Text>
          <Text style={styles.value}>CloverShield Financial Services</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Investigator:</Text>
          <Text style={styles.value}>{analystName || 'System Analyst'}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Submission Date:</Text>
          <Text style={styles.value}>{new Date().toLocaleString()}</Text>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Transaction Summary</Text>
        <View style={styles.table}>
          <View style={[styles.tableRow, { backgroundColor: '#F9FAFB' }]}>
            <View style={styles.tableCol}><Text style={[styles.tableCell, { fontWeight: 'bold' }]}>Type</Text></View>
            <View style={styles.tableCol}><Text style={[styles.tableCell, { fontWeight: 'bold' }]}>Amount</Text></View>
            <View style={styles.tableCol}><Text style={[styles.tableCell, { fontWeight: 'bold' }]}>Sender</Text></View>
            <View style={styles.tableCol}><Text style={[styles.tableCell, { fontWeight: 'bold' }]}>Receiver</Text></View>
            <View style={styles.tableCol}><Text style={[styles.tableCell, { fontWeight: 'bold' }]}>Time</Text></View>
          </View>
          {transactions.slice(0, 15).map((tx, i) => (
            <View key={i} style={styles.tableRow}>
              <View style={styles.tableCol}><Text style={styles.tableCell}>{tx.type}</Text></View>
              <View style={styles.tableCol}><Text style={styles.tableCell}>{tx.amount?.toFixed(2)}</Text></View>
              <View style={styles.tableCol}><Text style={styles.tableCell}>{tx.nameOrig}</Text></View>
              <View style={styles.tableCol}><Text style={styles.tableCell}>{tx.nameDest}</Text></View>
              <View style={styles.tableCol}><Text style={styles.tableCell}>{tx.step}</Text></View>
            </View>
          ))}
        </View>
        {transactions.length > 15 && <Text style={{ fontSize: 9, marginTop: 5, color: '#6B7280' }}>* Showing first 15 of {transactions.length} transactions</Text>}
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Investigator's Narrative (AI Draft)</Text>
        <Text style={styles.text}>{narrative}</Text>
      </View>



      <View style={styles.footer}>
        <Text>This report is generated automatically by the CloverShield Sovereign AI System. For official use only.</Text>
        <Text>Reference: {caseId} | Generated: {new Date().toISOString()}</Text>
      </View>
    </Page>
  </Document>
)

export const SARReportGenerator: React.FC<SARReportProps> = ({ caseId, transactions, analystNotes, analystName = "Analyst" }) => {
  const [narrative, setNarrative] = useState<string>('')
  const [loading, setLoading] = useState(false)
  const [ready, setReady] = useState(false)
  const [reportTransactions, setReportTransactions] = useState<any[]>([])

  const prepareReport = async () => {
    setLoading(true)
    try {
      // 1. Prepare data for PDF Report (Display-friendly strings)
      // We map timestamp to 'step' or a new 'time' field if we updated SARDocument, 
      // but for now re-using 'step' as the visual column for Time.
      const reportData = transactions.map(t => ({
        step: t.timestamp || t.step || 'N/A',
        type: t.transaction_type || t.type || 'TRANSFER',
        amount: parseFloat(t.amount),
        nameOrig: t.sender_id || t.nameOrig || 'Unknown',
        oldBalanceOrig: parseFloat(t.old_balance_orig || t.oldBalanceOrig || 0),
        newBalanceOrig: parseFloat(t.new_balance_orig || t.newBalanceOrig || 0),
        nameDest: t.receiver_id || t.nameDest || 'Unknown',
        oldBalanceDest: parseFloat(t.old_balance_dest || t.oldBalanceDest || 0),
        newBalanceDest: parseFloat(t.new_balance_dest || t.newBalanceDest || 0)
      })) as TransactionInput[]

      setReportTransactions(reportData)

      // 2. Prepare data for API (Strict Type Adherence)
      // API expects 'step' to be an integer (time step), NOT a string timestamp
      const apiTransactions = transactions.map(t => ({
        step: 1, // Defaulting to 1 as actual quantitative step is rarely used by LLM for narrative
        type: t.transaction_type || t.type || 'TRANSFER',
        amount: parseFloat(t.amount),
        nameOrig: t.sender_id || t.nameOrig || 'Unknown',
        oldBalanceOrig: parseFloat(t.old_balance_orig || t.oldBalanceOrig || 0),
        newBalanceOrig: parseFloat(t.new_balance_orig || t.newBalanceOrig || 0),
        nameDest: t.receiver_id || t.nameDest || 'Unknown',
        oldBalanceDest: parseFloat(t.old_balance_dest || t.oldBalanceDest || 0),
        newBalanceDest: parseFloat(t.new_balance_dest || t.newBalanceDest || 0)
      })) as TransactionInput[]

      const result = await generateSARNarrative(caseId, apiTransactions, analystNotes)
      setNarrative(result.narrative)
      setReady(true)
    } catch (error: any) {
      console.error("Failed to generate narrative", error)
      // Extract specific error if available
      const specificError = error.message || "Unknown error"
      setNarrative(`Narrative generation failed: ${specificError}. Please fill manually.`)

      // Ensure PDF download is still possible if it wasn't set successfully above
      // (Though it sets before the API call now, so this is just a fallback)
      if (reportTransactions.length === 0) {
        const reportData = transactions.map(t => ({
          step: t.timestamp || t.step || 'N/A',
          type: t.transaction_type || t.type || 'TRANSFER',
          amount: parseFloat(t.amount),
          nameOrig: t.sender_id || t.nameOrig || 'Unknown',
          oldBalanceOrig: parseFloat(t.old_balance_orig || t.oldBalanceOrig || 0),
          newBalanceOrig: parseFloat(t.new_balance_orig || t.newBalanceOrig || 0),
          nameDest: t.receiver_id || t.nameDest || 'Unknown',
          oldBalanceDest: parseFloat(t.old_balance_dest || t.oldBalanceDest || 0),
          newBalanceDest: parseFloat(t.new_balance_dest || t.newBalanceDest || 0)
        })) as TransactionInput[]
        setReportTransactions(reportData)
      }
      setReady(true)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="flex flex-col gap-4">
      {!ready ? (
        <button
          onClick={prepareReport}
          disabled={loading}
          className="bg-emerald-600 hover:bg-emerald-500 text-white px-4 py-2 rounded flex items-center justify-center gap-2 font-mono text-sm transition-all disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {loading ? (
            <>
              <Icon name="sync" className="animate-spin" /> Generating Report...
            </>
          ) : (
            <>
              <Icon name="description" /> Generate SAR (AI Draft)
            </>
          )}
        </button>
      ) : (
        <PDFDownloadLink
          document={<SARDocument caseId={caseId} transactions={reportTransactions} narrative={narrative} analystName={analystName} />}
          fileName={`SAR_${caseId}.pdf`}
          className="bg-teal-600 hover:bg-teal-500 text-white px-4 py-2 rounded flex items-center justify-center gap-2 font-mono text-sm transition-all shadow-[0_0_15px_rgba(13,148,136,0.4)]"
        >
          {({ blob, url, loading, error }) =>
            loading ? 'Preparing PDF...' : <><Icon name="download" /> Download Official SAR PDF</>
          }
        </PDFDownloadLink>
      )}

      {ready && (
        <div className="mt-2 p-3 bg-slate-900/50 border border-slate-700 rounded text-xs text-slate-400 font-mono">
          <strong>AI Narrative Preview:</strong>
          <p className="mt-1 italic opacity-80 line-clamp-3">{narrative}</p>
        </div>
      )}
    </div>
  )
}
